### ISSUE TITLE
How to generate the communication file

### ISSUE THREAD

**Issue by lixiangnlp** [hltcoe/concrete-python#5]
I want to try the concrete_inspect.py script. Could you give me a detailed example about the usage of concrete. Thanks.

**Comment by cjmay** [comment]
First of all, I am very sorry no one responded to you!

The [README](https://github.com/hltcoe/concrete-python/blob/master/README.rst) has been updated with examples for concrete-inspect.py, would you let us know if it clears up the usage for you, or if you are no longer considering using concrete-python?
